Repository StreetLamb/tribe, pull requests merged in 2024-08, with the labels that each got.

#93 Enhance nodes UI to display useful information at a glance
  frontend/src/components/ReactFlow/Nodes/FreelancerNode.tsx
  frontend/src/components/ReactFlow/Nodes/MemberNode.tsx
  frontend/src/components/ReactFlow/Nodes/RootNode.tsx
Labels: feature

#94 add showcase image to readme
  README.md
Labels: docs

#95 Add missing image to readme
  img/travel-planner-team.png
Labels: bug, docs

#96 Update environment values to prevent conflicts with external postgres instances.
  .env.example
  backend/app/alembic/env.py
Labels: bug

#97 Use MultiHostUrl build method to compute PG_DATABASE_URI
  backend/app/core/config.py
Labels: refactor

#99 Fix read threads result order
  backend/app/api/routes/threads.py
Labels: bug

#100 Add USER_AGENT value in env file to remove user agent warning in console
  .env.example
  docker-compose.yml
Labels: refactor

#98 Enable ollama models as agents
  README.md
  backend/app/alembic/versions/0a354b5c6f6c_create_writes_table.py
  backend/app/alembic/versions/38a9c73bfce2_add_base_url_col_to_members_table.py
  backend/app/alembic/versions/3a8a5f819c5f_add_thread_table.py
  backend/app/alembic/versions/6fa42be09dd2_add_checkpoints_table.py
  backend/app/core/graph/build.py
  backend/app/core/graph/members.py
  backend/app/models.py
  backend/poetry.lock
  backend/pyproject.toml
  frontend/src/client/models/MemberCreate.ts
  frontend/src/client/models/MemberOut.ts
  frontend/src/client/models/MemberUpdate.ts
  frontend/src/client/schemas/$MemberCreate.ts
  frontend/src/client/schemas/$MemberOut.ts
  frontend/src/client/schemas/$MemberUpdate.ts
  frontend/src/components/Members/EditMember.tsx
Labels: feature

#101 Display the search score in retriever message when retrieving documents
  frontend/src/components/Teams/ChatTeam.tsx
Labels: feature

#102 Simplify custom tool creation example
  backend/app/core/graph/skills/__init__.py
  backend/app/core/graph/skills/calculator.py
Labels: refactor

#103 Save fetched documents in history
  backend/app/core/graph/checkpoint/utils.py
  backend/app/core/graph/members.py
  backend/app/core/graph/messages.py
  backend/app/core/graph/skills/retriever_tool.py
Labels: feature

#104 show uploads selected as tags on MemberNode and FreelancerNode
  frontend/src/components/ReactFlow/Nodes/FreelancerNode.tsx
  frontend/src/components/ReactFlow/Nodes/MemberNode.tsx
Labels: bug

#113 Remove unused serpapi variables in .env.example
  .env.example
Labels: refactor

#114 Update .env.example
  .env.example
Labels: refactor

#117 Refactor to use enhanced postgres checkpointer
  backend/app/alembic/versions/20f584dc80d2_upgrade_checkpointer.py
  backend/app/core/config.py
  backend/app/core/graph/build.py
  backend/app/core/graph/checkpoint/postgres.py
  backend/app/core/graph/checkpoint/utils.py
  backend/app/models.py
  backend/poetry.lock
  backend/pyproject.toml
Labels: refactor, breaking

#118 Allow langgraph's recursion_limit to be configured through env variables
  .env.example
  backend/app/core/config.py
  backend/app/core/graph/build.py
  docker-compose.yml
Labels: feature

#121 Fix unable to delete thread bug
  backend/app/models.py
Labels: bug

#122 Reduce docker privilages to use non-root for FE
  docker-compose.yml
  frontend/Dockerfile
  frontend/nginx.conf
Labels: security

#129 Allow sequential agents to wait for human input
  backend/app/core/graph/build.py
  backend/app/core/graph/checkpoint/utils.py
  backend/app/core/graph/skills/__init__.py
  backend/app/core/graph/skills/human_tool.py
  backend/app/models.py
  backend/poetry.lock
  backend/pyproject.toml
  frontend/src/client/models/Interrupt.ts
  frontend/src/client/models/InterruptDecision.ts
  frontend/src/client/schemas/$Interrupt.ts
  frontend/src/components/Members/EditMember.tsx
  frontend/src/components/Teams/ChatTeam.tsx
Labels: feature

#132 Add flower for monitoring celery
  .env.example
  .github/workflows/deploy-production.yml
  .github/workflows/deploy-staging.yml
  backend/README.md
  backend/poetry.lock
  backend/pyproject.toml
  copier.yml
  deployment.md
  development.md
  docker-compose.override.yml
  docker-compose.yml
  local-deployment.md
Labels: feature

#133 Set max-memory-per-child value for celery to fix memory leak issue
  .env.example
  docker-compose.yml
Labels: bug

#134 Fix threads table overflowing if query text is long
  frontend/src/components/Teams/ViewThreads.tsx
Labels: bug
